# Ace of Shades 2 Client Configuration
# Set these properties to connect to a server.
serverHost: localhost
serverPort: 25565
username: player

# Settings for input.
input:
  mouseSensitivity: 0.005
# Settings for display.
display:
  fullscreen: true
  captureCursor: true
  fov: 80